services:
  documentdb:
    image: ghcr.io/microsoft/documentdb/documentdb:latest
    container_name: documentdb-oss
    ports:
      - "27017:27017"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - documentdb_data:/var/lib/postgresql/data

volumes:
  documentdb_data:
